import type { Resource, CommunityEvent } from "@/types/community";

export const sampleResources: Resource[] = [
  {
    id: "1",
    name: { en: "IRCO - Immigrant & Refugee Community Organization", es: "IRCO - Organización Comunitaria de Inmigrantes y Refugiados" },
    description: {
      en: "Comprehensive services for immigrants and refugees including employment, education, health, and social services. Multilingual staff available.",
      es: "Servicios integrales para inmigrantes y refugiados incluyendo empleo, educación, salud y servicios sociales. Personal multilingüe disponible.",
    },
    category: "education",
    address: "10301 NE Glisan St, Portland, OR 97220",
    phone: "(503) 234-1541",
    website: "https://irco.org",
    languages_spoken: ["en", "es", "vi", "zh", "ru"],
    latitude: 45.5267,
    longitude: -122.5558,
    verified: true,
  },
  {
    id: "2",
    name: { en: "El Programa Hispano Católico", es: "El Programa Hispano Católico" },
    description: {
      en: "Social services for the Latino community including immigration legal assistance, family support, food assistance, and workforce development.",
      es: "Servicios sociales para la comunidad latina incluyendo asistencia legal de inmigración, apoyo familiar, asistencia alimentaria y desarrollo laboral.",
    },
    category: "legal",
    address: "2740 SE Powell Blvd #7, Portland, OR 97202",
    phone: "(503) 232-9511",
    languages_spoken: ["en", "es"],
    latitude: 45.4972,
    longitude: -122.6377,
    verified: true,
  },
  {
    id: "3",
    name: { en: "Oregon Food Bank - Gateway Distribution", es: "Banco de Alimentos de Oregon - Distribución Gateway" },
    description: {
      en: "Free food distribution for Gateway residents. No ID or proof of income required. Culturally relevant food options available.",
      es: "Distribución gratuita de alimentos para residentes de Gateway. No se requiere identificación ni prueba de ingresos.",
    },
    category: "food",
    address: "7900 NE 33rd Dr, Portland, OR 97211",
    phone: "(503) 282-0555",
    website: "https://oregonfoodbank.org",
    languages_spoken: ["en", "es", "vi", "ru"],
    latitude: 45.5689,
    longitude: -122.6278,
    verified: true,
  },
  {
    id: "4",
    name: { en: "Wallace Medical Concern", es: "Wallace Medical Concern" },
    description: {
      en: "Free and low-cost healthcare for uninsured and underinsured residents. Primary care, dental, vision, and behavioral health services.",
      es: "Atención médica gratuita y de bajo costo para residentes sin seguro. Servicios de atención primaria, dental, visión y salud mental.",
    },
    category: "health",
    address: "12550 SE Stark St, Portland, OR 97233",
    phone: "(503) 489-1760",
    languages_spoken: ["en", "es", "vi"],
    latitude: 45.5189,
    longitude: -122.5367,
    verified: true,
  },
  {
    id: "5",
    name: { en: "Home Forward - Gateway Housing", es: "Home Forward - Vivienda Gateway" },
    description: {
      en: "Public housing authority providing affordable housing, Section 8 vouchers, and housing assistance programs for low-income families.",
      es: "Autoridad de vivienda pública que proporciona vivienda asequible, vales Sección 8 y programas de asistencia de vivienda.",
    },
    category: "housing",
    address: "135 SW Ash St, Portland, OR 97204",
    phone: "(503) 802-8300",
    website: "https://homeforward.org",
    languages_spoken: ["en", "es", "vi", "zh", "ru"],
    latitude: 45.5222,
    longitude: -122.6763,
    verified: true,
  },
  {
    id: "6",
    name: { en: "WorkSystems - East Portland Center", es: "WorkSystems - Centro Este Portland" },
    description: {
      en: "Employment services including job training, resume assistance, career counseling, and connections to local employers. Programs for youth and adults.",
      es: "Servicios de empleo incluyendo capacitación laboral, asistencia con currículum y conexiones con empleadores locales.",
    },
    category: "employment",
    address: "1001 SE 135th Ave, Portland, OR 97233",
    phone: "(503) 478-7300",
    website: "https://worksystems.org",
    languages_spoken: ["en", "es"],
    latitude: 45.5167,
    longitude: -122.5256,
    verified: true,
  },
  {
    id: "7",
    name: { en: "Self Enhancement Inc. (SEI)", es: "Self Enhancement Inc. (SEI)" },
    description: {
      en: "Youth development organization providing tutoring, mentoring, college preparation, and leadership programs for young people in East Portland.",
      es: "Organización de desarrollo juvenil que ofrece tutoría, mentoría, preparación universitaria y programas de liderazgo.",
    },
    category: "youth",
    address: "3920 N Kerby Ave, Portland, OR 97227",
    phone: "(503) 249-1721",
    website: "https://selfenhancement.org",
    languages_spoken: ["en"],
    latitude: 45.5567,
    longitude: -122.6718,
    verified: true,
  },
  {
    id: "8",
    name: { en: "East Portland Community Center", es: "Centro Comunitario del Este de Portland" },
    description: {
      en: "Senior services including meals, activities, transportation assistance, and social connections. Also serves as a cooling/warming center.",
      es: "Servicios para adultos mayores incluyendo comidas, actividades, asistencia de transporte y conexiones sociales.",
    },
    category: "senior",
    address: "740 SE 106th Ave, Portland, OR 97216",
    phone: "(503) 823-4000",
    languages_spoken: ["en", "es", "vi", "zh", "ru"],
    latitude: 45.5156,
    longitude: -122.5558,
    verified: true,
  },
  // --- Civic & Neighborhood Associations ---
  {
    id: "9",
    name: { en: "Hazelwood Neighborhood Association", es: "Asociación de Vecinos de Hazelwood" },
    description: {
      en: "Your local neighborhood association covering the Gateway/Hazelwood area (I-205 to 122nd, Halsey to Division). Meets the 3rd Monday of every month. Focuses on land use, public safety, Gateway transit development, and livability.",
      es: "Su asociación de vecinos local que cubre el área de Gateway/Hazelwood. Se reúne el 3er lunes de cada mes. Enfocada en uso de suelo, seguridad pública y desarrollo de tránsito.",
    },
    category: "civic",
    phone: "(503) 823-4550",
    website: "https://www.hnapdx.org/",
    languages_spoken: ["en"],
    verified: true,
  },
  {
    id: "10",
    name: { en: "Argay Terrace Neighborhood Association", es: "Asociación de Vecinos de Argay Terrace" },
    description: {
      en: "Neighborhood association north of Gateway covering NE Halsey to Columbia Blvd, 122nd to 141st. Board meets the 4th Wednesday of every month, 6:30-8:00 PM at Portland Fire Department Training Center (4800 NE 122nd Ave). No meeting in July.",
      es: "Asociación de vecinos al norte de Gateway. La junta se reúne el 4to miércoles de cada mes, 6:30-8:00 PM en el Centro de Entrenamiento de Bomberos de Portland.",
    },
    category: "civic",
    address: "4800 NE 122nd Ave, Portland, OR 97230",
    website: "http://www.argayterrace.org/",
    languages_spoken: ["en"],
    latitude: 45.5567,
    longitude: -122.5367,
    verified: true,
  },
  {
    id: "11",
    name: { en: "Parkrose Neighborhood Association", es: "Asociación de Vecinos de Parkrose" },
    description: {
      en: "Neighborhood association northwest of Gateway covering NE Sandy to Columbia, 102nd to 122nd. Meets the 3rd Tuesday of every month at 7 PM at Rossi Farms. No meetings in August, November, or December.",
      es: "Asociación de vecinos al noroeste de Gateway. Se reúne el 3er martes de cada mes a las 7 PM en Rossi Farms. Sin reuniones en agosto, noviembre o diciembre.",
    },
    category: "civic",
    email: "parkroseneighbors@gmail.com",
    website: "https://historicparkrose.com/",
    languages_spoken: ["en"],
    verified: true,
  },
  {
    id: "12",
    name: { en: "Russell Neighborhood Association", es: "Asociación de Vecinos de Russell" },
    description: {
      en: "Neighborhood association south of Glisan, roughly 108th to 122nd down to Division. Meets the 1st Thursday of every month at 6 PM via Zoom. Email to receive meeting invite link.",
      es: "Asociación de vecinos al sur de Glisan. Se reúne el 1er jueves de cada mes a las 6 PM por Zoom. Envíe un correo electrónico para recibir el enlace de la reunión.",
    },
    category: "civic",
    email: "RussellNeighborhood@gmail.com",
    languages_spoken: ["en"],
    verified: true,
  },
  {
    id: "13",
    name: { en: "Glenfair Neighborhood Association", es: "Asociación de Vecinos de Glenfair" },
    description: {
      en: "Neighborhood association east of Hazelwood covering 148th to 162nd, Halsey to Division. Contact East Portland Community Office for current meeting schedule.",
      es: "Asociación de vecinos al este de Hazelwood. Comuníquese con la Oficina Comunitaria del Este de Portland para el horario actual de reuniones.",
    },
    category: "civic",
    phone: "(503) 823-4550",
    languages_spoken: ["en"],
    verified: true,
  },
  {
    id: "14",
    name: { en: "Mill Park Neighborhood Association", es: "Asociación de Vecinos de Mill Park" },
    description: {
      en: "Neighborhood association south of Hazelwood covering 102nd to 122nd, Division south. Contact East Portland Community Office for current meeting schedule.",
      es: "Asociación de vecinos al sur de Hazelwood. Comuníquese con la Oficina Comunitaria del Este de Portland para el horario actual de reuniones.",
    },
    category: "civic",
    phone: "(503) 823-4550",
    languages_spoken: ["en"],
    verified: true,
  },
  {
    id: "15",
    name: { en: "Centennial Community Association", es: "Asociación Comunitaria de Centennial" },
    description: {
      en: "Community association for outer East Portland, roughly 136th to 174th, south of Burnside. Contact East Portland Community Office for current meeting schedule.",
      es: "Asociación comunitaria para el extremo este de Portland. Comuníquese con la Oficina Comunitaria del Este de Portland para el horario actual.",
    },
    category: "civic",
    phone: "(503) 823-4550",
    languages_spoken: ["en"],
    verified: true,
  },
  {
    id: "16",
    name: { en: "East Portland Action Plan (EPAP)", es: "Plan de Acción del Este de Portland (EPAP)" },
    description: {
      en: "Primary advocacy and policy voice for East Portland equity, infrastructure, anti-displacement, parks, transit, and community voice. General meetings on the 4th Wednesday of every month at 6:30 PM (online/hybrid). Multiple subcommittees on land use, public safety, economic development.",
      es: "Voz principal de defensa y políticas para la equidad del Este de Portland. Reuniones generales el 4to miércoles de cada mes a las 6:30 PM (en línea/híbrido).",
    },
    category: "civic",
    email: "eastportlandactionplan@gmail.com",
    website: "https://eastportlandactionplan.org",
    languages_spoken: ["en", "es", "vi", "zh", "ru"],
    verified: true,
  },
  {
    id: "17",
    name: { en: "Gateway Area Business Association (GABA)", es: "Asociación de Negocios del Área de Gateway (GABA)" },
    description: {
      en: "Business advocacy for the Gateway district. Focuses on Gateway Discovery Park, Gateway Green, transit-oriented development, street improvements on NE Halsey/Weidler, and public safety. Monthly meetings — check website for current schedule.",
      es: "Defensa empresarial para el distrito de Gateway. Enfocada en el Parque Gateway Discovery, desarrollo orientado al tránsito y mejoras en la calle NE Halsey/Weidler.",
    },
    category: "civic",
    address: "11124 NE Halsey St PMB 478, Portland, OR 97220",
    website: "https://gatewaybusiness.org/",
    languages_spoken: ["en"],
    verified: true,
  },
  {
    id: "18",
    name: { en: "East Portland Community Office (EPCO)", es: "Oficina Comunitaria del Este de Portland (EPCO)" },
    description: {
      en: "City of Portland district office supporting 13 volunteer neighborhood associations east of I-205. Provides meeting space, community resources, and organizational support. Located in the Nick Fish Building.",
      es: "Oficina distrital de la Ciudad de Portland que apoya 13 asociaciones de vecinos voluntarias al este de la I-205. Proporciona espacio de reunión y recursos comunitarios.",
    },
    category: "civic",
    address: "10540 NE Halsey St, Portland, OR 97220",
    phone: "(503) 823-4550",
    email: "EPCO@PortlandOregon.gov",
    website: "https://www.portland.gov/civic/myneighborhood/epconeighborhoods",
    languages_spoken: ["en", "es", "vi", "zh", "ru"],
    latitude: 45.5310,
    longitude: -122.5528,
    verified: true,
  },
  {
    id: "19",
    name: { en: "Friends of Gateway Green", es: "Amigos de Gateway Green" },
    description: {
      en: "Community advocacy group for the 25-acre Gateway Green nature and bike park at the I-205/I-84 interchange. Volunteer restoration events and trail maintenance opportunities.",
      es: "Grupo comunitario de defensa del parque natural y de bicicletas Gateway Green de 25 acres. Oportunidades de restauración voluntaria y mantenimiento de senderos.",
    },
    category: "civic",
    website: "https://gatewaygreen.org",
    languages_spoken: ["en"],
    verified: true,
  },
];

export const sampleEvents: CommunityEvent[] = [
  {
    id: "1",
    title: { en: "Gateway Community Meeting", es: "Reunión Comunitaria de Gateway" },
    description: {
      en: "Monthly community meeting to discuss the Gateway Confluence strategic plan. Interpretation available in Spanish, Vietnamese, and Chinese. Childcare provided.",
      es: "Reunión comunitaria mensual para discutir el plan estratégico de Gateway Confluence. Interpretación disponible en español, vietnamita y chino. Se proporciona cuidado infantil.",
    },
    category: "community",
    location_name: "East Portland Community Center",
    start_time: "2026-03-15T18:00:00-07:00",
    end_time: "2026-03-15T20:00:00-07:00",
    languages: ["en", "es", "vi", "zh"],
    is_virtual: false,
    contact_name: "Gateway Confluence Coalition",
  },
  {
    id: "2",
    title: { en: "Small Business Support Workshop", es: "Taller de Apoyo a Pequeños Negocios" },
    description: {
      en: "Free workshop for Gateway small business owners covering bookkeeping basics, permit navigation, and available grants. Presented in English and Spanish.",
      es: "Taller gratuito para propietarios de pequeños negocios de Gateway sobre contabilidad básica, navegación de permisos y subvenciones disponibles.",
    },
    category: "business",
    location_name: "IRCO",
    start_time: "2026-03-22T10:00:00-07:00",
    end_time: "2026-03-22T13:00:00-07:00",
    languages: ["en", "es"],
    is_virtual: false,
  },
  {
    id: "3",
    title: { en: "Gateway Cultures Festival Planning", es: "Planificación del Festival Cultural de Gateway" },
    description: {
      en: "Join us to plan the first annual Gateway Cultures Festival! We need volunteers, performers, food vendors, and organizers from all of Gateway's cultural communities.",
      es: "Únase para planificar el primer Festival Cultural anual de Gateway. Necesitamos voluntarios, artistas, vendedores de comida y organizadores.",
    },
    category: "culture",
    location_name: "Gateway Discovery Park",
    start_time: "2026-04-05T14:00:00-07:00",
    end_time: "2026-04-05T16:00:00-07:00",
    languages: ["en", "es", "vi", "zh", "ru"],
    is_virtual: false,
  },
  {
    id: "4",
    title: { en: "Housing Rights Know Your Rights", es: "Conozca Sus Derechos de Vivienda" },
    description: {
      en: "Virtual workshop on tenant rights in Oregon. Learn about eviction protections, rent increase rules, and how to get help. Available in Vietnamese.",
      es: "Taller virtual sobre derechos de inquilinos en Oregon. Aprenda sobre protecciones contra desalojo y reglas de aumento de renta.",
    },
    category: "housing",
    start_time: "2026-04-10T18:30:00-07:00",
    end_time: "2026-04-10T20:00:00-07:00",
    languages: ["en", "vi"],
    is_virtual: true,
    contact_name: "Community Alliance of Tenants",
  },
  // --- Neighborhood Association Meetings ---
  {
    id: "5",
    title: { en: "Hazelwood Neighborhood Association Meeting", es: "Reunión de la Asociación de Vecinos de Hazelwood" },
    description: {
      en: "Monthly meeting of the Hazelwood Neighborhood Association. Discuss land use, public safety, Gateway transit development, and neighborhood livability. All Hazelwood residents welcome.",
      es: "Reunión mensual de la Asociación de Vecinos de Hazelwood. Discusión sobre uso de suelo, seguridad pública y desarrollo de tránsito en Gateway.",
    },
    category: "civic",
    location_name: "East Portland Community Center",
    start_time: "2026-03-16T19:00:00-07:00",
    end_time: "2026-03-16T20:00:00-07:00",
    languages: ["en"],
    is_virtual: false,
    contact_name: "Hazelwood Neighborhood Association",
  },
  {
    id: "6",
    title: { en: "Parkrose Neighborhood Association Meeting", es: "Reunión de la Asociación de Vecinos de Parkrose" },
    description: {
      en: "Monthly meeting of the Parkrose Neighborhood Association at Rossi Farms. Open to all Parkrose residents. No meetings in August, November, or December.",
      es: "Reunión mensual de la Asociación de Vecinos de Parkrose en Rossi Farms. Abierta a todos los residentes de Parkrose.",
    },
    category: "civic",
    location_name: "Rossi Farms",
    start_time: "2026-03-17T19:00:00-07:00",
    end_time: "2026-03-17T20:30:00-07:00",
    languages: ["en"],
    is_virtual: false,
    contact_name: "Parkrose Neighborhood Association",
  },
  {
    id: "7",
    title: { en: "Argay Terrace Neighborhood Association Board Meeting", es: "Reunión de la Junta de la Asociación de Vecinos de Argay Terrace" },
    description: {
      en: "Monthly board meeting of the Argay Terrace Neighborhood Association at the Portland Fire Department Training Center. All Argay residents welcome. No meeting in July.",
      es: "Reunión mensual de la junta de Argay Terrace en el Centro de Entrenamiento de Bomberos de Portland. Sin reunión en julio.",
    },
    category: "civic",
    location_name: "Portland Fire Dept Training Center",
    address: "4800 NE 122nd Ave, Portland, OR 97230",
    start_time: "2026-03-25T18:30:00-07:00",
    end_time: "2026-03-25T20:00:00-07:00",
    languages: ["en"],
    is_virtual: false,
    contact_name: "Argay Terrace Neighborhood Association",
  },
  {
    id: "8",
    title: { en: "East Portland Action Plan General Meeting", es: "Reunión General del Plan de Acción del Este de Portland" },
    description: {
      en: "Monthly general meeting of the East Portland Action Plan. Advocacy for East Portland equity, infrastructure, anti-displacement, parks, and transit. Online/hybrid format.",
      es: "Reunión general mensual del Plan de Acción del Este de Portland. Defensa de la equidad, infraestructura, anti-desplazamiento, parques y tránsito.",
    },
    category: "civic",
    start_time: "2026-03-25T18:30:00-07:00",
    end_time: "2026-03-25T20:30:00-07:00",
    languages: ["en", "es", "vi", "zh", "ru"],
    is_virtual: true,
    contact_name: "East Portland Action Plan",
    contact_email: "eastportlandactionplan@gmail.com",
  },
  {
    id: "9",
    title: { en: "Russell Neighborhood Association Meeting", es: "Reunión de la Asociación de Vecinos de Russell" },
    description: {
      en: "Monthly meeting of the Russell Neighborhood Association via Zoom. Email RussellNeighborhood@gmail.com for the meeting link.",
      es: "Reunión mensual de la Asociación de Vecinos de Russell por Zoom. Envíe un correo a RussellNeighborhood@gmail.com para el enlace.",
    },
    category: "civic",
    start_time: "2026-04-02T18:00:00-07:00",
    end_time: "2026-04-02T19:30:00-07:00",
    languages: ["en"],
    is_virtual: true,
    contact_name: "Russell Neighborhood Association",
    contact_email: "RussellNeighborhood@gmail.com",
  },
  {
    id: "10",
    title: { en: "Hazelwood Neighborhood Association Meeting — April", es: "Reunión de Hazelwood — Abril" },
    description: {
      en: "Monthly meeting of the Hazelwood Neighborhood Association. Third Monday of every month.",
      es: "Reunión mensual de la Asociación de Vecinos de Hazelwood. Tercer lunes de cada mes.",
    },
    category: "civic",
    location_name: "East Portland Community Center",
    start_time: "2026-04-20T19:00:00-07:00",
    end_time: "2026-04-20T20:00:00-07:00",
    languages: ["en"],
    is_virtual: false,
    contact_name: "Hazelwood Neighborhood Association",
  },
  {
    id: "11",
    title: { en: "Parkrose Neighborhood Association Meeting — April", es: "Reunión de Parkrose — Abril" },
    description: {
      en: "Monthly meeting at Rossi Farms. Third Tuesday of every month.",
      es: "Reunión mensual en Rossi Farms. Tercer martes de cada mes.",
    },
    category: "civic",
    location_name: "Rossi Farms",
    start_time: "2026-04-21T19:00:00-07:00",
    end_time: "2026-04-21T20:30:00-07:00",
    languages: ["en"],
    is_virtual: false,
    contact_name: "Parkrose Neighborhood Association",
  },
  {
    id: "12",
    title: { en: "Argay Terrace NA Board Meeting — April", es: "Reunión de Argay Terrace — Abril" },
    description: {
      en: "Monthly board meeting. Fourth Wednesday of every month.",
      es: "Reunión mensual de la junta. Cuarto miércoles de cada mes.",
    },
    category: "civic",
    location_name: "Portland Fire Dept Training Center",
    address: "4800 NE 122nd Ave, Portland, OR 97230",
    start_time: "2026-04-22T18:30:00-07:00",
    end_time: "2026-04-22T20:00:00-07:00",
    languages: ["en"],
    is_virtual: false,
    contact_name: "Argay Terrace Neighborhood Association",
  },
  {
    id: "13",
    title: { en: "EPAP General Meeting — April", es: "Reunión General EPAP — Abril" },
    description: {
      en: "Monthly general meeting. Fourth Wednesday of every month. Online/hybrid.",
      es: "Reunión general mensual. Cuarto miércoles de cada mes. En línea/híbrido.",
    },
    category: "civic",
    start_time: "2026-04-22T18:30:00-07:00",
    end_time: "2026-04-22T20:30:00-07:00",
    languages: ["en", "es", "vi", "zh", "ru"],
    is_virtual: true,
    contact_name: "East Portland Action Plan",
    contact_email: "eastportlandactionplan@gmail.com",
  },
];

export const resourceCategories = [
  "housing",
  "legal",
  "food",
  "health",
  "education",
  "employment",
  "youth",
  "senior",
  "civic",
] as const;
