import type { Resource, CommunityEvent } from "@/types/community";

export const sampleResources: Resource[] = [
  {
    id: "1",
    name: { en: "IRCO - Immigrant & Refugee Community Organization", es: "IRCO - Organización Comunitaria de Inmigrantes y Refugiados" },
    description: {
      en: "Comprehensive services for immigrants and refugees including employment, education, health, and social services. Multilingual staff available.",
      es: "Servicios integrales para inmigrantes y refugiados incluyendo empleo, educación, salud y servicios sociales. Personal multilingüe disponible.",
    },
    category: "education",
    address: "10301 NE Glisan St, Portland, OR 97220",
    phone: "(503) 234-1541",
    website: "https://irco.org",
    languages_spoken: ["en", "es", "vi", "zh", "ru"],
    latitude: 45.5267,
    longitude: -122.5558,
    verified: true,
  },
  {
    id: "2",
    name: { en: "El Programa Hispano Católico", es: "El Programa Hispano Católico" },
    description: {
      en: "Social services for the Latino community including immigration legal assistance, family support, food assistance, and workforce development.",
      es: "Servicios sociales para la comunidad latina incluyendo asistencia legal de inmigración, apoyo familiar, asistencia alimentaria y desarrollo laboral.",
    },
    category: "legal",
    address: "2740 SE Powell Blvd #7, Portland, OR 97202",
    phone: "(503) 232-9511",
    languages_spoken: ["en", "es"],
    latitude: 45.4972,
    longitude: -122.6377,
    verified: true,
  },
  {
    id: "3",
    name: { en: "Oregon Food Bank - Gateway Distribution", es: "Banco de Alimentos de Oregon - Distribución Gateway" },
    description: {
      en: "Free food distribution for Gateway residents. No ID or proof of income required. Culturally relevant food options available.",
      es: "Distribución gratuita de alimentos para residentes de Gateway. No se requiere identificación ni prueba de ingresos.",
    },
    category: "food",
    address: "7900 NE 33rd Dr, Portland, OR 97211",
    phone: "(503) 282-0555",
    website: "https://oregonfoodbank.org",
    languages_spoken: ["en", "es", "vi", "ru"],
    latitude: 45.5689,
    longitude: -122.6278,
    verified: true,
  },
  {
    id: "4",
    name: { en: "Wallace Medical Concern", es: "Wallace Medical Concern" },
    description: {
      en: "Free and low-cost healthcare for uninsured and underinsured residents. Primary care, dental, vision, and behavioral health services.",
      es: "Atención médica gratuita y de bajo costo para residentes sin seguro. Servicios de atención primaria, dental, visión y salud mental.",
    },
    category: "health",
    address: "12550 SE Stark St, Portland, OR 97233",
    phone: "(503) 489-1760",
    languages_spoken: ["en", "es", "vi"],
    latitude: 45.5189,
    longitude: -122.5367,
    verified: true,
  },
  {
    id: "5",
    name: { en: "Home Forward - Gateway Housing", es: "Home Forward - Vivienda Gateway" },
    description: {
      en: "Public housing authority providing affordable housing, Section 8 vouchers, and housing assistance programs for low-income families.",
      es: "Autoridad de vivienda pública que proporciona vivienda asequible, vales Sección 8 y programas de asistencia de vivienda.",
    },
    category: "housing",
    address: "135 SW Ash St, Portland, OR 97204",
    phone: "(503) 802-8300",
    website: "https://homeforward.org",
    languages_spoken: ["en", "es", "vi", "zh", "ru"],
    latitude: 45.5222,
    longitude: -122.6763,
    verified: true,
  },
  {
    id: "6",
    name: { en: "WorkSystems - East Portland Center", es: "WorkSystems - Centro Este Portland" },
    description: {
      en: "Employment services including job training, resume assistance, career counseling, and connections to local employers. Programs for youth and adults.",
      es: "Servicios de empleo incluyendo capacitación laboral, asistencia con currículum y conexiones con empleadores locales.",
    },
    category: "employment",
    address: "1001 SE 135th Ave, Portland, OR 97233",
    phone: "(503) 478-7300",
    website: "https://worksystems.org",
    languages_spoken: ["en", "es"],
    latitude: 45.5167,
    longitude: -122.5256,
    verified: true,
  },
  {
    id: "7",
    name: { en: "Self Enhancement Inc. (SEI)", es: "Self Enhancement Inc. (SEI)" },
    description: {
      en: "Youth development organization providing tutoring, mentoring, college preparation, and leadership programs for young people in East Portland.",
      es: "Organización de desarrollo juvenil que ofrece tutoría, mentoría, preparación universitaria y programas de liderazgo.",
    },
    category: "youth",
    address: "3920 N Kerby Ave, Portland, OR 97227",
    phone: "(503) 249-1721",
    website: "https://selfenhancement.org",
    languages_spoken: ["en"],
    latitude: 45.5567,
    longitude: -122.6718,
    verified: true,
  },
  {
    id: "8",
    name: { en: "East Portland Community Center", es: "Centro Comunitario del Este de Portland" },
    description: {
      en: "Senior services including meals, activities, transportation assistance, and social connections. Also serves as a cooling/warming center.",
      es: "Servicios para adultos mayores incluyendo comidas, actividades, asistencia de transporte y conexiones sociales.",
    },
    category: "senior",
    address: "740 SE 106th Ave, Portland, OR 97216",
    phone: "(503) 823-4000",
    languages_spoken: ["en", "es", "vi", "zh", "ru"],
    latitude: 45.5156,
    longitude: -122.5558,
    verified: true,
  },
];

export const sampleEvents: CommunityEvent[] = [
  {
    id: "1",
    title: { en: "Gateway Community Meeting", es: "Reunión Comunitaria de Gateway" },
    description: {
      en: "Monthly community meeting to discuss the Gateway Confluence strategic plan. Interpretation available in Spanish, Vietnamese, and Chinese. Childcare provided.",
      es: "Reunión comunitaria mensual para discutir el plan estratégico de Gateway Confluence. Interpretación disponible en español, vietnamita y chino. Se proporciona cuidado infantil.",
    },
    category: "community",
    location_name: "East Portland Community Center",
    address: "740 SE 106th Ave, Portland, OR 97216",
    start_time: "2026-03-15T18:00:00-07:00",
    end_time: "2026-03-15T20:00:00-07:00",
    languages: ["en", "es", "vi", "zh"],
    is_virtual: false,
    contact_name: "Gateway Confluence Coalition",
    contact_email: "info@gatewayconfluence.org",
  },
  {
    id: "2",
    title: { en: "Small Business Support Workshop", es: "Taller de Apoyo a Pequeños Negocios" },
    description: {
      en: "Free workshop for Gateway small business owners covering bookkeeping basics, permit navigation, and available grants. Presented in English and Spanish.",
      es: "Taller gratuito para propietarios de pequeños negocios de Gateway sobre contabilidad básica, navegación de permisos y subvenciones disponibles.",
    },
    category: "business",
    location_name: "IRCO",
    address: "10301 NE Glisan St, Portland, OR 97220",
    start_time: "2026-03-22T10:00:00-07:00",
    end_time: "2026-03-22T13:00:00-07:00",
    languages: ["en", "es"],
    is_virtual: false,
    contact_email: "business@gatewayconfluence.org",
  },
  {
    id: "3",
    title: { en: "Gateway Cultures Festival Planning", es: "Planificación del Festival Cultural de Gateway" },
    description: {
      en: "Join us to plan the first annual Gateway Cultures Festival! We need volunteers, performers, food vendors, and organizers from all of Gateway's cultural communities.",
      es: "Únase para planificar el primer Festival Cultural anual de Gateway. Necesitamos voluntarios, artistas, vendedores de comida y organizadores.",
    },
    category: "culture",
    location_name: "Gateway Discovery Park",
    address: "9800 NE Halsey St, Portland, OR 97220",
    start_time: "2026-04-05T14:00:00-07:00",
    end_time: "2026-04-05T16:00:00-07:00",
    languages: ["en", "es", "vi", "zh", "ru"],
    is_virtual: false,
  },
  {
    id: "4",
    title: { en: "Housing Rights Know Your Rights", es: "Conozca Sus Derechos de Vivienda" },
    description: {
      en: "Virtual workshop on tenant rights in Oregon. Learn about eviction protections, rent increase rules, and how to get help. Available in Vietnamese.",
      es: "Taller virtual sobre derechos de inquilinos en Oregon. Aprenda sobre protecciones contra desalojo y reglas de aumento de renta.",
    },
    category: "housing",
    start_time: "2026-04-10T18:30:00-07:00",
    end_time: "2026-04-10T20:00:00-07:00",
    languages: ["en", "vi"],
    is_virtual: true,
    virtual_link: "https://zoom.us/example",
    contact_name: "Community Alliance of Tenants",
  },
];

export const resourceCategories = [
  "housing",
  "legal",
  "food",
  "health",
  "education",
  "employment",
  "youth",
  "senior",
] as const;
